version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build-and-publish-frontend:
    machine: true
    steps:
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/$FRONTEND_IMAGE_NAME
          tag: $CIRCLE_BRANCH
          path-to-dockerfile: ../frontend/Dockerfile
  build-and-publish-backend:
    machine: true
    steps:
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/$BACKEND_IMAGE_NAME
          tag: $CIRCLE_BRANCH
          path-to-dockerfile: ../backend/Dockerfile
workflows:
  version: 2
  build:
    jobs:
      - build-and-publish-backend
      - build-and-publish-frontend
