version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/$FRONTEND_IMAGE_NAME
          tag: $CIRCLE_BRANCH
          path-to-dockerfile: ../frontend/Dockerfile
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/$BACKEND_IMAGE_NAME
          tag: $CIRCLE_BRANCH
          path-to-dockerfile: ../backend/Dockerfile
