version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/frontend
          tag: $CIRCLE_BRANCH
          path: ~/project/frontend/
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/backend
          tag: $CIRCLE_BRANCH
          path: ~/project/backend/
